package sharedServices

import (
	"encoding/json"
	"errors"
	"fmt"
	"my-api/internal/services"
	"my-api/internal/services/helpers"
	"my-api/internal/services/shared/decisions"
	"my-api/internal/utils"
	"my-api/pkg"
	"strings"
)

// interpretLLMDecision interprets a decision string generated by the LLM and dispatches it to the appropriate handler.
func interpretLLMDecision(Phase string, Checksum string, GamePrompt string) (string, error) {
	switch Phase {
	case "Discussion":
		return decisions.HandleTalkToLogic(Checksum, GamePrompt)
	case "Voting":
		return decisions.HandleVotingLogic(Checksum, GamePrompt)
	default:
		pkg.DisplayContext("Unknown data phase.", pkg.Error)
		return "", fmt.Errorf(`unknown data phase "%s"`, Phase)
	}
}

// askLLMForDecision builds a user prompt, sends it to the LLM, and returns the generated decision.
func askLLMForDecision(Message string, Checksum string) (string, error) {
	discussion, err := helpers.GetAllDiscussions(Checksum)
	if err != nil {
		return "", err
	}

	Message += "\nDiscussion: {" + discussion + "}"

	// Read the "WhoToTalk.txt" file to get the system prompt
	systemPrompt, err := services.ReadPromptFromFile("prompts/WhoToTalk.txt")
	if err != nil {
		return "", fmt.Errorf("error retrieving the system prompt: %w", err)
	}

	decision, err := services.GptSimpleRequest(Message, systemPrompt)
	if err != nil {
		pkg.DisplayContext("GptSimpleRequest failed:", pkg.Error, err)
		return "", err
	}

	return decision, nil
}

func shouldMakeDecision(Message string, Checksum string, GamePrompt string) (bool, error) {
	discussion, err := helpers.GetAllDiscussions(Checksum)
	if err != nil {
		return false, err
	}

	Message += "\nDiscussion: {" + discussion + "}"

	// Read the "ShouldTalk.txt" file to get the system prompt
	systemPrompt, err := services.ReadPromptFromFile("prompts/ShouldTalk.txt")

	systemPrompt = strings.Replace(systemPrompt, "{Game Prompt Here}", GamePrompt, 1)

	if err != nil {
		return false, fmt.Errorf("error retrieving the system prompt: %w", err)
	}

	response, err := services.GptSimpleRequest(Message, systemPrompt)
	if err != nil {
		pkg.DisplayContext("GptSimpleRequest failed:", pkg.Error, err)
		return false, err
	}

	if strings.Contains(response, "Speak: yes") {
		pkg.DisplayContext("IA decided to speak", pkg.Debug)
		return true, nil
	} else if strings.Contains(response, "Speak: no") {
		pkg.DisplayContext("IA decided not to speak : "+response, pkg.Debug)
		return false, nil
	} else {
		pkg.DisplayContext("Cannot get response format in shouldMakeDecision", pkg.Error)
		return false, fmt.Errorf("cannot get response format in shouldMakeDecision")
	}
}

// MakeDecisionService checks access rights, queries the LLM for a decision, and interprets the response.
func MakeDecisionService(EnvironmentData string, Checksum string, Token string) (map[string]string, error) {
	userID, err := utils.GetUserIDFromJWT(Token)
	if err != nil {
		return nil, err
	}

	val, err := helpers.IsMyEntity(Checksum, userID)
	if err != nil {
		return nil, err
	}

	gamePrompt, err := services.GetGamePromptByUserID(userID)

	if err != nil {
		pkg.DisplayContext("Cannot fetch game prompt:", pkg.Error, err)
		return nil, err
	}

	if !val {
		return nil, errors.New("access denied to this entity")
	}

	var data map[string]string

	err = json.Unmarshal([]byte(EnvironmentData), &data)
	if err != nil {
		pkg.DisplayContext("Cannot unmarshal environment data:", pkg.Error, err)
		return nil, err
	}

	task, err := interpretLLMDecision(data["phase"], Checksum, gamePrompt)
	if err != nil {
		pkg.DisplayContext("Error after LLM response interpretation:", pkg.Error, err)
		return nil, err
	}

	err = json.Unmarshal([]byte(task), &data)
	if err != nil {
		pkg.DisplayContext("Cannot unmarshal task:", pkg.Error, err)
		return nil, err
	}

	if data["Action"] == "TalkTo" {
		err = NewMessageService(Checksum, []string{"Everyone"}, data["Message"], Token)
		if err != nil {
			pkg.DisplayContext("Error after inserting new message:", pkg.Error, err)
			return nil, err
		}
		return data, nil
	} else if data["Action"] == "VoteFor" {
		return data, nil
	} else {
		pkg.DisplayContext("Unknown Action: "+data["Action"], pkg.Error)
		return nil, errors.New("unknown action")
	}
}
