name: Run Tests with Docker Compose

on:
  push:
    branches: [ main, dev, refacto ]
  pull_request:
    branches: [ main, dev, refacto ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Copy .env.example to .env
        run: cp .env.exemple .env.local

      - name: Build and start services
        run: docker-compose up -d

      - name: Wait for API (max 440s)
        run: |
          for i in {1..120}; do
            if curl -s http://localhost:3000/health | grep "OK"; then
              echo "✅ API is up"
              break
            fi
            echo "Waiting for API..."
            sleep 2
          done

      - name: Run Go tests
        run: go test -v ./tests

      - name: Shutdown
        run: docker-compose down
