name: Run Tests with Docker Compose

on:
  push:
    branches: [ main, dev, refacto ]
  pull_request:
    branches: [ main, dev, refacto ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Copy .env.example to .env
        run: cp .env.exemple .env.local

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Wait for API to launch (120s)
        run: |
          sleep 120

      - name: Run Go tests
        run: go test -v ./tests

      - name: Shutdown
        run: docker-compose down
