name: Run Tests with Docker Compose

on:
  push:
    branches: [ main, dev, refacto ]
  pull_request:
    branches: [ main, dev, refacto ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set Up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Copy .env.example to .env
        run: cp .env.exemple .env.local

      - name: Build and start services
        run: docker-compose up -d

      - name: Wait for health endpoint
        run: |
          chmod +x ./script/wait-for-it.sh
          ./script/wait-for-it.sh

      - name: Run Go tests
        run: go test -v ./tests

      - name: Shutdown
        run: docker-compose down
