name: Run Tests with Docker Compose

on:
  push:
    branches: [ main, dev, refacto ]
  pull_request:
    branches: [ main, dev, refacto ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CHATGPT_TOKEN: ${{ secrets.CHATGPT_TOKEN }}

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set Up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Copy .env.workflow to .env
        run: cp .env.workflow .env.local

      - name: Build and start services
        run: docker-compose up -d

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            response=$(curl -s http://localhost:3000/health || true)
            if [ "$response" = "OK" ]; then
            echo "✅ API is ready"
            exit 0
            fi
            sleep 1
          done
          echo "❌ API did not respond OK in time"
          docker-compose logs api
          exit 1

      - name: Run Go tests
        run: go test -v ./tests

      - name: Shutdown
        run: docker-compose down

      - name: Show container logs
        if: failure()
        run: docker-compose logs
